# Generated by Django 6.0.6 on 2026-06-20 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Введите заголовок",
                        max_length=50,
                        null=True,
                        verbose_name="Заголовок",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Введите содержимое",
                        verbose_name="Содержимое",
                    ),
                ),
                (
                    "preview",
                    models.ImageField(
                        blank=True,
                        help_text="Вставьте изображение",
                        null=True,
                        upload_to="blogs/",
                        verbose_name="Превью",
                    ),
                ),
                (
                    "create_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Введите дату создания",
                        verbose_name="Дата создания",
                    ),
                ),
                (
                    "is_publication",
                    models.BooleanField(
                        default=False,
                        help_text="Укажите признак публикации",
                        verbose_name="Признак публикации",
                    ),
                ),
                (
                    "counter_view",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Введите количество просмотров",
                        verbose_name="Количество просмотров",
                    ),
                ),
            ],
            options={
                "verbose_name": "блог",
                "verbose_name_plural": "блоги",
            },
        ),
    ]
