# Generated by Django 6.0.6 on 2026-07-12 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["name"],
                "permissions": [("can_unpublish_product", "Can unpublish product")],
                "verbose_name": "продукт",
                "verbose_name_plural": "продукты",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="status",
            field=models.CharField(
                choices=[("published", "Опубликован"), ("unpublished", "Не опубликован")],
                default="unpublished",
                max_length=20,
                verbose_name="Статус публикации",
            ),
        ),
    ]
